import type { QueryRunner } from 'typeorm';

export const extractTableDefinitions = async (
  queryRunner: QueryRunner,
  schemaName: string,
): Promise<string[]> => {
  const rows: { ddl: string }[] = await queryRunner.query(
    `SELECT
      'CREATE TABLE "' || n.nspname || '"."' || c.relname || '" (' || E'\n' ||
      string_agg(
        '  "' || a.attname || '" ' || format_type(a.atttypid, a.atttypmod) ||
        CASE WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
             WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
             ELSE ''
        END ||
        CASE WHEN ad.adbin IS NOT NULL AND a.attidentity = ''
                  AND format_type(a.atttypid, a.atttypmod) != 'tsvector'
             THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
             ELSE ''
        END ||
        CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END,
        ',' || E'\n'
        ORDER BY a.attnum
      ) || E'\n);' AS ddl
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_attribute a ON a.attrelid = c.oid
    LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
    WHERE n.nspname = $1
      AND c.relkind IN ('r', 'p')
      AND a.attnum > 0
      AND NOT a.attisdropped
    GROUP BY n.nspname, c.relname
    ORDER BY c.relname`,
    [schemaName],
  );

  return rows.map((row) => row.ddl);
};
